version: '3.1'
services :
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_trab2
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080